"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.timezone = exports.utc = exports.dayjs = void 0;
var dayjs = require("dayjs");
exports.dayjs = dayjs;
var utc = require("dayjs/plugin/utc");
exports.utc = utc;
var timezone = require("dayjs/plugin/timezone");
exports.timezone = timezone;
dayjs.extend(utc);
dayjs.extend(timezone);
